begin: "2000-01-01 00:00:00"
end: "2000-01-01 23:59:59"
log_file: sample_ble.csv
result_dir_name:

win_size: 2

beacon_dir: beacon
enable_clear_map: True
enable_draw_beacons: False
enable_save_img: False
enable_save_video: False
frame_rate: 1
map_conf_file: sample.yaml
map_img_file: sample.pgm
map_show_policy: 3
map_show_range:
win_stride: 1

truth_log_file:

el_correction: 2
enable_write_conf: False
propag_coef: 5

win_policy: 1

log_lerp_freq: 1
max_blank_len: 2

trilaterate_policy: 2

max_use_beacon_num: 3

# tentative
direct_sd: 1
max_particle_stride: 25
rand_pos_range: 375
lost_resample_policy: 1
dist_sd: 37.5
estim_pos_policy: 2
neg_weight_coef: 0
