# log
begin: "2000-01-01 00:00:00"
end: "2000-01-01 23:59:59"
lerp_freq: 1
max_blank_len: 2

# triangulation
lerp_win_policy: 1
triangulate_policy: 2
max_use_beacon_num: 3

# particle filter
enable_truth: False

map_img_file: sample.pgm
map_conf_file: sample.yaml
enable_clear_map: True
enable_draw_beacons: False
map_show_policy: 1

enable_save_video: False
enable_save_img: False
file_name:
frame_rate: 1

win_size: 2
win_stride: 1
win_policy: 1

max_particle_stride: 32
direct_sd: 4.5
lost_resample_policy: 2

propag_coef: 4
el_correction: 2
dist_sd: 64
